# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# 2. Given a NumPy array 'arr', check if its data type is float64.


In [4]:
arr = np.array([1.5, 2.6, 3.7])

print('Datatype:', arr.dtype)

Datatype: float64


# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers

In [5]:
arr = np.array([1,3,2+3j, 33, 4+7j, 3+7j])
print(arr)

[ 1.+0.j  3.+0.j  2.+3.j 33.+0.j  4.+7.j  3.+7.j]


# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [6]:

arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)

print("Converted array (float32):", arr_float32)

Converted array (float32): [1. 2. 3. 4. 5.]


# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [7]:
import numpy as np
arr = np.array([1.23456789, 2.3456789, 3.456789, 4.56789])
arr_float32 = arr.astype(np.float32)
print("Original array (float64):", arr)
print("Converted array (float32):", arr_float32)


Original array (float64): [1.23456789 2.3456789  3.456789   4.56789   ]
Converted array (float32): [1.2345679 2.3456788 3.456789  4.56789  ]


# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype

In [22]:
arr = np.array(input("type arr"))
attributes = (arr)
print(arr.shape)
print(arr.size)
arr.dtype



type arr4
()
1


dtype('<U1')

# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [ ]:
arr_1d = np.array([1, 2, 3, 4])
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Dimensionality of arr_1d:", array_dimension(arr_1d))  
print("Dimensionality of arr_2d:", array_dimension(arr_2d))
print("Dimensionality of arr_3d:", array_dimension(arr_3d))   


# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

item_size, total_size = item_size_info(arr)

print("Item size (bytes):", item_size)   
print("Total size (bytes):", total_size)   


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape of the array:", shape)     
print("Strides of the array:", strides) 


# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements 

In [ ]:
n = 5
zeros_arr = create_zeros_array(n)
print("Zeros array of length", n, ":", zeros_arr)


# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`

In [ ]:

rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print("Ones matrix of size", rows, "x", cols, ":\n", ones_matrix)


# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step`.

In [ ]:

start = 1
stop = 10
step = 2
range_arr = generate_range_array(start, stop, step)
print("Range array from", start, "to", stop, "with step", step, ":\n", range_arr)


# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [ ]:
start = 1.0
stop = 2.0
num = 5
linspace_arr = generate_linear_space(start, stop, num)
print("Linearly spaced array from", start, "to", stop, "with", num, "values:\n", linspace_arr)


# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square  matrix of size `n x n` using `numpy.eye`.

In [ ]:
n = 4
identity_matrix = create_identity_matrix(n)
print(f"Identity matrix of size {n} x {n}:\n", identity_matrix)


# 16. Write a function that takes a Python list and converts it into a NumPy array

In [ ]:
pyhon = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print("Python list:", python_list)
print("NumPy array:", numpy_array)


# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [8]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_array = original_array.view()
view_array[0, 0] = 100
print("Original array:\n", original_array)
print("View array:\n", view_array)


Original array:
 [[100   2   3]
 [  4   5   6]]
View array:
 [[100   2   3]
 [  4   5   6]]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [15]:
import numpy as np
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
result = concatenate_arrays(array1, array2, axis=0)
print(result)
result = concatenate_arrays(array1, array2, axis=1)
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

In [10]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]]) 
array2 = np.array([[7], [8]])  
result = np.hstack((array1, array2))
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Concatenated Array:\n", result)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[7]
 [8]]
Concatenated Array:
 [[1 2 3 7]
 [4 5 6 8]]


# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [23]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
array3 = np.array([[9, 10], [11, 12]])
stacked_result =([array1, array2, array3])
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Array 3:\n", array3)
print("Vertically Stacked Result:\n", stacked_result)

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Array 3:
 [[ 9 10]
 [11 12]]
Vertically Stacked Result:
 [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size

In [12]:
start = 10
stop = 30
step = 6
print(f"Array of integers from {start} to {stop} (inclusive) with step size {step}:")
print(result)

Array of integers from 10 to 30 (inclusive) with step size 6:
[[1 2 3 7]
 [4 5 6 8]]


# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [13]:
values = generate_equal_spaced_values()
print(values)



NameError: name 'generate_equal_spaced_values' is not defined

# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [24]:
def create_log_space_array(start, stop, num_values):
    return np.logspace(np.log10(start), np.log10(stop), num=num_values)
log_space_array = create_log_space_array(1, 1000, 5)
print(log_space_array)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [15]:
import pandas as pd
import numpy as np
def create_random_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])
    return df

df = create_random_dataframe()
print(df)


   Column1  Column2  Column3
0       96       85        9
1       24       29       30
2       33       10       17
3       24       47       49
4       83       98       43


# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [16]:
def replace_negatives_with_zero(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {'A': [1, -2, 3, -4, 5], 'B': [10, 20, -30, 40, -50]}
df = pd.DataFrame(data)
print("Before replacing negatives:")
print(df)

df = replace_negatives_with_zero(df, 'A')
print("\nAfter replacing negatives in column 'A':")
print(df)


Before replacing negatives:
   A   B
0  1  10
1 -2  20
2  3 -30
3 -4  40
4  5 -50

After replacing negatives in column 'A':
   A   B
0  1  10
1  0  20
2  3 -30
3  0  40
4  5 -50


In [17]:
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)

30


# 27. Retrieve the element at index (1, 2) from the 2D NumPy array

In [18]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]
print(element)

6


# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [19]:
arr = np.array([3, 8, 2, 10, 5, 7])
mask = arr > 5
filtered_arr = arr[mask]
print(filtered_arr)

[ 8 10  7]


# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy ar

In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_arr = arr[2:6]
print(sliced_arr)

[3 4 5 6]


# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [21]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [22]:
def extract_elements(arr_2d, indices):
    return arr_2d[indices[:, 0], indices[:, 1]]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([[0, 1], 
                    [1, 2], 
                    [2, 0]])

extracted_elements = extract_elements(arr_2d, indices)
print(extracted_elements)


[2 6 7]


# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [23]:
def filter_elements(arr, threshold):
    mask = arr > threshold
    filtered_arr = arr[mask]
    return filtered_arr
arr = np.array([1, 5, 10, 3, 7, 8])
threshold = 5

filtered_elements = filter_elements(arr, threshold)
print(filtered_elements)

[10  7  8]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [24]:
def extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    return arr_3d[indices_dim1, indices_dim2, indices_dim3]
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

indices_dim1 = np.array([0, 1]) 
indices_dim2 = np.array([0, 1]) 
indices_dim3 = np.array([1, 2])  

extracted_elements = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print(extracted_elements)


[ 2 12]


# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [25]:
def filter_elements_with_conditions(arr, condition1, condition2):
    mask = (condition1) & (condition2)
    filtered_arr = arr[mask]
    return filtered_arr
arr = np.array([1, 5, 10, 3, 7, 8])
condition1 = arr > 3
condition2 = arr < 8
filtered_elements = filter_elements_with_conditions(arr, condition1, condition2)
print(filtered_elements)


[5 7]


# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [26]:
import numpy as np

def extract_elements_2d(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_indices = np.array([0, 1, 2]) 
col_indices = np.array([1, 2, 0]) 
extracted_elements = extract_elements_2d(arr_2d, row_indices, col_indices)
print(extracted_elements)

[2 6 7]


# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [27]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr_plus_5 = arr + 5
print(arr_plus_5)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [28]:
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])
result = arr1.T * arr2
print(result)

[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [29]:
arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]]) 
arr1_reshaped = arr1.T  
result = arr2 + arr1_reshaped
print(result)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [30]:
arr1 = np.array([[1], [2], [3]])  
arr2 = np.array([[4, 5, 6]])     
result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility

In [31]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  
arr2 = np.array([[7, 8],
                 [9, 10]])   
arr2_reshaped = arr2[:, :, np.newaxis]  
arr1_reshaped = arr1[:, np.newaxis, :] 
result = arr1_reshaped * arr2_reshaped
print(result)

[[[ 7 14 21]
  [ 8 16 24]]

 [[36 45 54]
  [40 50 60]]]


# 41. Calculate column wise mean for the given array:

In [32]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)

[2.5 3.5 4.5]


# 42. Find maximum value in each row of the given array:

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_max = np.max(arr, axis=0)
print(column_max)


[4 5 6]


# 43. For the given array, find indices of maximum value in each column.

In [34]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
column_max_indices = np.argmax(arr, axis=0)
print(column_max_indices)

[1 1 1]


# 44. For the given array, apply custom function to calculate moving sum along rows.

In [35]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
def moving_sum(arr):
    return np.convolve(arr, np.ones(2, dtype=int), 'valid')
moving_sums = np.apply_along_axis(moving_sum, 1, arr)
print(moving_sums)

[[ 3  5]
 [ 9 11]]


# 45. In the given array, check if all elements in each column are even

In [36]:
arr = np.array([[2, 4, 6],
                [3, 5, 7]])
are_all_even = np.all(arr % 2 == 0, axis=0)
print(are_all_even)

[False False False]


# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

In [29]:
original_array = np.array([1, 2, 3, 4, 5, 6])
m, n = 2, 3 

reshaped_matrix = original_array.reshape(m, n)
print(reshaped_matrix)

[[1 2 3]
 [4 5 6]]


# 47. Create a function that takes a matrix as input and returns the flattened array.

In [38]:
def flatten_matrix(matrix):
    return matrix.flatten()
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])
flattened_array = flatten_matrix(input_matrix)
print(flattened_array)

[1 2 3 4 5 6]


# 48. Write a function that concatenates two given arrays along a specified axis

In [31]:
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])
concatenated_axis0 = concatenate_arrays(array1, array2, axis=0)
concatenated_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenated along axis 0:")
print(concatenated_axis0)
print("\nConcatenated along axis 1:")
print(concatenated_axis1)


Concatenated along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


# 49. Create a function that splits an array into multiple sub-arrays along a specified axis# 49. Create a function that splits an array into multiple sub-arrays along a specified axis

In [37]:
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_arrays = np.split(original_array, 3, axis=1)  # Split along axis 1 into 3 sub-arrays
print(sub_arrays)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


# 50. Write a function that inserts and then deletes elements from a given array at specified indices

In [41]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
def insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):
    for idx, value in zip(indices_to_insert, values_to_insert):
        arr = np.insert(arr, idx, value)
    arr = np.delete(arr, indices_to_delete)
    return arr
result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Resulting array:", result_array)

Resulting array: [ 1 10 11  4  5]


# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [38]:
arr1 = np.random.randint(1, 100)
arr2 = np.arange(1, 11)  
result = arr1 + arr2
print("arr1:")
print(arr1)
print("\narr2:")
print(arr2)
print("\nResult of element-wise addition:")
print(result)


arr1:
1

arr2:
[ 1  2  3  4  5  6  7  8  9 10]

Result of element-wise addition:
[ 2  3  4  5  6  7  8  9 10 11]


# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [43]:
arr1 = np.arange(10, 0, -1)  
arr2 = np.arange(1, 11)  
result = arr1 - arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise subtraction:")
print(result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [44]:
arr1 = np.random.randint(1, 10, size=(3, 5)) 
arr2 = np.arange(1, 6) 
result = arr1 * arr2
print("arr1:")
print(result)

arr1:
[[ 1  4 12 20 35]
 [ 1  8  9 16  5]
 [ 4  6  3 36 10]]


# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [45]:
arr1 = np.arange(2, 11, 2)  
arr2 = np.arange(1, 6) 
result = arr1 / arr2
print("arr1:", arr1)
print("arr2:", arr2)
print(result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
[2. 2. 2. 2. 2.]


# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [46]:
arr1 = np.arange(1, 6) 
arr2 = arr1[::-1]  
result = arr1 ** arr2 
print("arr1:", arr1)
print("arr2:", arr2)
print(result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
[ 1 16 27 16  5]


# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [47]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
def count_substring_occurrences(arr, substring):
    arr_list = arr.tolist()
    count = 0
    for s in arr_list:
        count += s.count(substring)
    return count
substring_to_count = 'hello'
occurrences = count_substring_occurrences(arr, substring_to_count)
print(f"Occurrences of '{substring_to_count}' in the array: {occurrences}")


Occurrences of 'hello' in the array: 3


# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [48]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase_characters(arr):
    arr_list = arr.tolist()
    uppercase_chars = []
    for s in arr_list:
        uppercase_chars.extend([ch for ch in s if ch.isupper()])
    return uppercase_chars
uppercase_chars = extract_uppercase_characters(arr)
print( uppercase_chars)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [49]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr, substring, new_substring):
    arr_list = arr.tolist()
    new_arr = np.array([s.replace(substring, new_substring) for s in arr_list])
    return new_arr
substring_to_replace = 'apple'
new_substring = 'orange'
modified_arr = replace_substring(arr, substring_to_replace, new_substring)
print("Modified array:")
print(modified_arr)

Modified array:
['orange' 'banana' 'grape' 'pineorange']


# 59. Write a function that concatenates strings in a NumPy array element-wise

In [50]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def concatenate_strings(arr):
    arr_list = arr.tolist()
    concatenated_string = ''.join(arr_list)
    return concatenated_string
concatenated_string = concatenate_strings(arr)
print( concatenated_string)

applebananagrapepineapple


# 59. Write a function that concatenates strings in a NumPy array element-wise.

In [51]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
def concatenate_strings_element_wise(arr1, arr2):
    concatenated_array = np.core.defchararray.add(arr1, arr2)
    return concatenated_array
concatenated_array = concatenate_strings_element_wise(arr1, arr2)
print("Concatenated array:")
print(concatenated_array)

Concatenated array:
['HelloOpen' 'WorldAI']


# 60. Write a function that finds the length of the longest string in a NumPy array.

In [52]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def longest_string_length(arr):
    arr_list = arr.tolist()
    max_length = max(len(s) for s in arr_list)
    return max_length
longest_len = longest_string_length(arr)
print("Length :", longest_len)

Length : 9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [53]:
df = np.random.randint(1, 1001, size=100)
mean_value = np.mean(df)
median_value = np.median(df)
var_value = np.var(df)
std_deviation_value = np.std(df)

print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Variance: {var_value}")
print(f"Standard Deviation: {std_deviation_value}")


Mean: 497.58
Median: 494.0
Variance: 91801.80360000001
Standard Deviation: 302.9881245197574


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [54]:
random_numbers = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")



25th Percentile: 18.5
75th Percentile: 78.75


# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function

In [55]:
array1 = np.random.randint(1, 101, size=100)
array2 = np.random.randint(1, 101, size=100)
correlation = np.corrcoef(array1, array2)[0, 1]

print(f"Correlation: {correlation}")


Correlation: -0.12363361353726542


# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function

In [56]:
matrix1 = np.random.randint(1, 10, size=(3, 4))
matrix2 = np.random.randint(1, 10, size=(4, 3))
result_matrix = np.dot(matrix1, matrix2)
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of matrix multiplication:")
print(result_matrix)

Matrix 1:
[[7 2 1 6]
 [9 5 5 1]
 [6 4 8 1]]

Matrix 2:
[[6 9 3]
 [8 5 4]
 [8 7 7]
 [4 2 6]]

Result of matrix multiplication:
[[ 90  92  72]
 [138 143  88]
 [136 132  96]]


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [57]:
random_int = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(random_int, 10)
percentile_50 = np.percentile(random_int, 50)
percentile_90 = np.percentile(random_int, 90)
first_quartile = np.percentile(random_int, 25)
third_quartile = np.percentile(random_int, 75)
print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile: {first_quartile}")
print(f"Third Quartile: {third_quartile}")

10th Percentile: 133.7
50th Percentile (Median): 590.0
90th Percentile: 862.4
First Quartile: 296.25
Third Quartile: 719.75


# 66. Create a NumPy array of integers and find the index of a specific element.

In [58]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
element_to_find = 70
index = np.where(array == element_to_find)[0]
if index.size > 0:
    print(f"The index of the element {element_to_find} is: {index[0]}")
else:
    print(f"The element {element_to_find} is not in the array")

The index of the element 70 is: 6


# 67. Generate a random NumPy array and sort it in ascending order.

In [59]:
random_array = np.random.randint(1, 101, size=20)
sorted_array = np.sort(random_array)

print("Random Array:")
print(random_array)
print("\nSorted Array in Ascending Order:")
print(sorted_array)


Random Array:
[97  1 10 87 75 99 64 19 13 78  1 15 83 32 16 81 59 13 32 33]

Sorted Array in Ascending Order:
[ 1  1 10 13 13 15 16 19 32 32 33 59 64 75 78 81 83 87 97 99]


# 68. Filter elements >20  in the given NumPy array.

In [60]:
arr = np.array([12, 25, 6, 42, 8, 30])
filtered_array = array[array > 20]

print(arr)
print(filtered_array)

[12 25  6 42  8 30]
[ 30  40  50  60  70  80  90 100]


# 69. Filter elements which are divisible by 3 from a given NumPy array.

In [61]:
arr = np.array([1, 5, 8, 12, 15])
mask = (arr % 3 == 0)
result = arr[mask]

print("Original array:", arr)
print("Elements divisible by 3:", result)


Original array: [ 1  5  8 12 15]
Elements divisible by 3: [12 15]


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [62]:
arr = np.array([10, 20, 30, 40, 50])
mask = (arr >= 20) & (arr <= 40)
result = arr[mask]

print("Original array:", arr)
print("Filtered elements:", result)

Original array: [10 20 30 40 50]
Filtered elements: [20 30 40]


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [63]:
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print("Array:", arr)
print("Byte order:", byte_order)


Array: [1 2 3]
Byte order: =


# 72. For the given NumPy array, perform byte swapping in place using `byteswap()

In [64]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
arr.byteswap(inplace=True)
print("after byte swapping:", arr)

Original array: [1 2 3]
after byte swapping: [16777216 33554432 50331648]


# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()

In [65]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
arr_swapped = arr.newbyteorder()
print("after swapping new byte order:", arr_swapped)

Original array: [1 2 3]
after swapping new byte order: [16777216 33554432 50331648]


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`

In [66]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array:", arr)
system_endian = '='
arr_swapped = arr.newbyteorder(system_endian)
print("Array after swapping byte order:", arr_swapped)

Original array: [1 2 3]
Array after swapping byte order: [1 2 3]


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`  attribute `byteorder`.

In [67]:
arr = np.array([1, 2, 3], dtype=np.int32)
system_byteorder = arr.dtype.byteorder
print("Current system's byte order:", system_byteorder)
if system_byteorder != '=':
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")

Current system's byte order: =
Byte swapping is not necessary.


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`

In [68]:
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
print("Original arr1:", arr1)
print("Copy copy_arr:", copy_arr)
copy_arr[0] = 100
print("\nAfter:")
print("arr1:", arr1)
print("copy_arr:", copy_arr)

Original arr1: [ 1  2  3  4  5  6  7  8  9 10]
Copy copy_arr: [ 1  2  3  4  5  6  7  8  9 10]

After:
arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [69]:
matrix = np.random.randint(1, 10, size=(3, 3))
print("Original matrix:")
print(matrix)
view_slice = matrix[1:, 1:]
print("\nSlice (view_slice) from matrix:")
print(view_slice)
view_slice[0, 0] = 100
print("\nAfter modifying:")
print("matrix:")
print(matrix)
print("view_slice:")
print(view_slice)

Original matrix:
[[5 3 6]
 [6 5 9]
 [4 5 6]]

Slice (view_slice) from matrix:
[[5 9]
 [5 6]]

After modifying:
matrix:
[[  5   3   6]
 [  6 100   9]
 [  4   5   6]]
view_slice:
[[100   9]
 [  5   6]]


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.


In [70]:
array_a = np.arange(1, 13).reshape(4, 3)
print("Original array_a:")
print(array_a)
view_b = array_a[2:, :2]
print("\nSlice (view_b) from array_a:")
print(view_b)
view_b += 5
print("\nAfter broadcasting addition of 5 :")
print("array_a:")
print(array_a)
print("view_b:")
print(view_b)

Original array_a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice (view_b) from array_a:
[[ 7  8]
 [10 11]]

After broadcasting addition of 5 :
array_a:
[[ 1  2  3]
 [ 4  5  6]
 [12 13  9]
 [15 16 12]]
view_b:
[[12 13]
 [15 16]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [71]:
orig_array = np.arange(1, 9).reshape(2, 4)
print("Original orig_array:")
print(orig_array)
reshaped_view = orig_array.reshape(4, 2)
print(reshaped_view)
reshaped_view[0, 0] = 100
print(orig_array)
print(reshaped_view)

Original orig_array:
[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[100   2   3   4]
 [  5   6   7   8]]
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [72]:
data = np.random.randint(1, 10, size=(3, 4))
print("Original data:")
print(data)
data_copy = data[data > 5].copy()
print("\nCopy (data_copy) of elements greater than 5:")
print(data_copy)
data_copy[0] = 100
print("\nAfter modifying:")
print("data:")
print(data)
print("data_copy:")
print(data_copy)

Original data:
[[2 5 5 1]
 [7 4 4 8]
 [4 2 4 5]]

Copy (data_copy) of elements greater than 5:
[7 8]

After modifying:
data:
[[2 5 5 1]
 [7 4 4 8]
 [4 2 4 5]]
data_copy:
[100   8]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [73]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8, 9],
              [10, 11, 12]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

addition_result = A + B
print("\n addition :")
print(addition_result)

subtraction_result = A - B
print("\n subtraction:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9]
 [10 11 12]]

 addition :
[[ 8 10 12]
 [14 16 18]]

 subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [74]:
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])
print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)
result = np.dot(C, D)
print("\nmultiplication:")
print(result)

Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

multiplication:
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


# 83. Create a matrix `E` and find its transpose

In [75]:
E = np.array([[1, 2, 3],[4, 5, 6]])
print("Matrix E:")
print(E)
E_transpose = E.T 
print("\nTranspose of matrix E:")
print(E_transpose)

Matrix E:
[[1 2 3]
 [4 5 6]]

Transpose of matrix E:
[[1 4]
 [2 5]
 [3 6]]


# 84. Generate a square matrix `F` and compute its determinant

In [76]:
F = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("Matrix F:")
print(F)
determinant_F = np.linalg.det(F)

print("\nDeterminant of matrix F:")
print(determinant_F)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F:
-9.51619735392994e-16


# 85. Create a square matrix `G` and find its inverse

In [77]:
G = np.array([[1, 2, 3],[0, 1, 0],[4, 5, 6]])
print("Matrix G:")
print(G)
try:
    inverse_G = np.linalg.inv(G)
    print("\nInverse of matrix G:")
    print(inverse_G)
except np.linalg.LinAlgError:
    print("\nMatrix G is singular and does not have an inverse.")

Matrix G:
[[1 2 3]
 [0 1 0]
 [4 5 6]]

Inverse of matrix G:
[[-1.         -0.5         0.5       ]
 [ 0.          1.          0.        ]
 [ 0.66666667 -0.5        -0.16666667]]
